# Generated by Django 4.2.20 on 2025-04-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news_crawler", "0002_news_delete_post"),
    ]

    operations = [
        migrations.RenameField(
            model_name="news",
            old_name="url",
            new_name="image_url",
        ),
        migrations.AddField(
            model_name="news",
            name="news_url",
            field=models.URLField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="news",
            name="paragraph",
            field=models.TextField(null=True),
        ),
    ]
