# Generated by Django 4.2.20 on 2025-04-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news_crawler", "0003_rename_url_news_image_url_news_news_url_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="News",
        ),
    ]
